create table if not exists usuarios (
    id bigint generated by default as identity,
    nome varchar(120) not null,
    email varchar(160) not null,
    telefone varchar(20),
    data_nascimento date,
    senha varchar(255) not null,
    created_at timestamp with time zone not null default now(),

    constraint usuarios_pk primary key (id),
    constraint usuarios_email_unico unique (email),
    constraint usuarios_nome_obrigatorio check (btrim(nome) <> ''),
    constraint usuarios_email_obrigatorio check (btrim(email) <> ''),
    constraint usuarios_senha_obrigatoria check (btrim(senha) <> '')
);

create table if not exists livros (
    id bigint generated by default as identity,
    nome_autor varchar(160) not null,
    titulo_livro varchar(200) not null,
    editora varchar(120),
    quantidade integer not null default 0,
    ano_publicacao integer,
    genero varchar(100),
    created_at timestamp with time zone not null default now(),

    constraint livros_pk primary key (id),
    constraint livros_autor_obrigatorio check (btrim(nome_autor) <> ''),
    constraint livros_titulo_obrigatorio check (btrim(titulo_livro) <> ''),
    constraint livros_quantidade_nao_negativa check (quantidade >= 0),
    constraint livros_ano_publicacao_valido check (
        ano_publicacao is null or ano_publicacao >= 0
    )
);

create table if not exists emprestimos (
    id bigint generated by default as identity,
    usuario_id bigint not null,
    livro_id bigint not null,
    data_emprestimo date not null default current_date,
    data_devolucao date,
    status varchar(20) not null default 'emprestado',
    created_at timestamp with time zone not null default now(),

    constraint emprestimos_pk primary key (id),
    constraint emprestimos_usuario_fk foreign key (usuario_id)
        references usuarios (id)
        on update cascade
        on delete restrict,
    constraint emprestimos_livro_fk foreign key (livro_id)
        references livros (id)
        on update cascade
        on delete restrict,
    constraint emprestimos_status_valido check (status in ('emprestado', 'devolvido')),
    constraint emprestimos_devolucao_coerente check (
        (
            status = 'emprestado'
            and data_devolucao is null
        )
        or (
            status = 'devolvido'
            and data_devolucao is not null
            and data_devolucao >= data_emprestimo
        )
    )
);
